#!/usr/bin/env ruby

require 'yaml'

module Pew
  class Builtins
    class << self
      def list
        methods.keep_if { |method| method.to_s.start_with?('builtin_') }
      end

      def builtin_tasks
        puts 'Available tasks:'
        Manager.pewdict.keys.map do |task|
          puts "  #{task}"
        end
      end

      def builtin_version
        puts 'Pew 0.0.6'
        puts 'Vladislav Andreev, <me@vld.by>'
        puts 'Since 2019.'
      end
      alias builtin_v builtin_version

      def builtin_pewfile
        pewfiles = Dir.glob(File.join(File.expand_path('~/**'), 'Pewfile')) 
        puts "You current Pewfile is: #{pewfiles.last}\n\n"

        if pewfiles.size > 1
            puts 'Also these Pewfiles have been found:'
            pewfiles[0..-2].each do |pewfile|
              puts " - #{pewfile}"
            end
        end
      end
      alias builtin_pewfiles builtin_pewfile

      def builtin_pew
        puts "Pew pew pew!"
      end
    end
  end

  class Manager
    class << self
      def pewdict
        pewfile = Dir.glob(File.join(File.expand_path('~/**'), 'Pewfile')).last
        unless pewfile
          puts "Can't find Pewfile in any of your directories"
          return
        end

        YAML.safe_load(File.read(pewfile))
      end
    end
  end

  # @param name [String] Task name
  class Task
    def initialize(name)
      @name = name

      if Builtins.list.include?(:"builtin_#{name}")
        Builtins.send(:"builtin_#{name}")
      else
        @commands = Manager.pewdict.fetch(name) do
          puts "Cannot find command `#{name}` in your Pewfile"
          return
        end

        execute(@commands)
      end
    end

    def execute(commands)
      commands.each do |command|
        puts system([command, ARGV.join(' ')].join(' '))
      end
    end
  end

  class CLI
    def initialize
      @argv = ARGV
      Task.new(ARGV.shift)
    end
  end
end

Pew::CLI.new
