#!/usr/bin/env ruby

require 'yaml'

module Pew
  class Builtins
    class << self
      def list
        methods.keep_if { |method| method.to_s.start_with?('builtin_') }
      end

      def builtin_tasks
        return unless (pewd = Manager.new.pewdict)

        puts 'Available tasks:'
        pewd.keys.map { |task| puts " - #{task}" }
      end

      def builtin_version
        puts 'Pew 0.0.8, https://github.com/vladyio/pew'
        puts 'Vladislav Andreev, <me@vld.by>'
        puts 'Since 2019.'
      end
      alias builtin_v builtin_version

      def builtin_pewfile
        puts Manager.new.pewfile
      end

      def builtin_pew
        puts 'Pew pew pew!'
      end
    end
  end

  class Manager
    def pewdict
      unless pewfile
        puts "Can't find Pewfile in any of parent directories"
        return
      end

      YAML.safe_load(File.read(pewfile))
    end

    def pewfile
      current_dir = Dir.pwd
      return current_dir << '/Pewfile' unless Dir.glob('Pewfile').empty?

      while current_dir != '/home'
        current_dir = File.expand_path("#{current_dir}/..")
        return current_dir << '/Pewfile' unless Dir.glob('Pewfile').empty?
      end

      nil
    end
  end

  # @param name [String] Task name
  class Task
    def initialize(name)
      @name = name

      if Builtins.list.include?(:"builtin_#{name}")
        Builtins.send(:"builtin_#{name}")
      else
        @commands = Manager.new.pewdict.fetch(name) do
          puts "Cannot find command `#{name}` in your Pewfile"
          return
        end

        execute(@commands)
      end
    end

    def execute(commands)
      commands.each do |command|
        puts system([command, ARGV.join(' ')].join(' '))
      end
    end
  end

  class CLI
    def initialize
      @argv = ARGV
      Task.new(ARGV.shift)
    end
  end
end

Pew::CLI.new
